name: 'Run .NET Tests'
description: 'Executes unit tests for a .NET project'

inputs:
  project-path:
    description: 'Path to the test project or solution'
    required: false
    default: '.'
  configuration:
    description: 'Test configuration (Debug/Release)'
    required: false
    default: 'Release'
  no-build:
    description: 'Skip building before running tests'
    required: false
    default: 'true'
  collect-coverage:
    description: 'Collect code coverage'
    required: false
    default: 'false'
  test-filter:
    description: 'Filter expression to select tests'
    required: false
    default: ''
  verbosity:
    description: 'Test verbosity level'
    required: false
    default: 'normal'

outputs:
  test-results-path:
    description: 'Path to test results'
    value: ${{ steps.test.outputs.results-path }}

runs:
  using: 'composite'
  steps:
    - name: Run tests
      id: test
      shell: bash
      working-directory: ${{ inputs.project-path }}
      run: |
        echo "Running tests for: ${{ inputs.project-path }}"
        
        TEST_ARGS="--configuration ${{ inputs.configuration }} --verbosity ${{ inputs.verbosity }}"
        TEST_ARGS="$TEST_ARGS --logger 'trx;LogFileName=test-results.trx'"
        TEST_ARGS="$TEST_ARGS --results-directory ./TestResults"
        
        if [ "${{ inputs.no-build }}" == "true" ]; then
          TEST_ARGS="$TEST_ARGS --no-build"
        fi
        
        if [ "${{ inputs.collect-coverage }}" == "true" ]; then
          TEST_ARGS="$TEST_ARGS --collect:'XPlat Code Coverage'"
        fi
        
        if [ -n "${{ inputs.test-filter }}" ]; then
          TEST_ARGS="$TEST_ARGS --filter '${{ inputs.test-filter }}'"
        fi
        
        dotnet test $TEST_ARGS
        
        echo "results-path=./TestResults" >> $GITHUB_OUTPUT
    
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results-${{ github.run_number }}
        path: ${{ inputs.project-path }}/TestResults/**/*