name: 'Setup .NET SDK'
description: 'Sets up the .NET SDK with caching support'

inputs:
  dotnet-version:
    description: '.NET SDK version to install'
    required: false
    default: '8.0.x'
  cache-dependencies:
    description: 'Enable NuGet package caching'
    required: false
    default: 'true'

runs:
  using: 'composite'
  steps:
    - name: Setup .NET SDK ${{ inputs.dotnet-version }}
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ inputs.dotnet-version }}
        cache: ${{ inputs.cache-dependencies == 'true' }}
        cache-dependency-path: '**/packages.lock.json'
    
    - name: Display .NET info
      shell: bash
      run: dotnet --info